services:
  rep2php8:
    build:
      context: .
      dockerfile: docker/Dockerfile
      additional_contexts:
# p2-repと2chproxy.plの参照するgitリポジトリの指定
        p2-rep2: https://github.com/fukumen/p2-php.git#php8-merge-mbstring
        2chproxy.pl: https://github.com/fukumen/2chproxy.pl.git#always-https-for-2ch-config
      args:
        DEBUG: off
    # image: rep2:latest
    image: ghcr.io/fukumen/rep2:latest
    volumes:
# rep2のデータの格納先の指定
      - ./rep2-data:/ext:Z
# php.iniを設定したいときの指定
#      - ./php-local.ini:/usr/local/etc/php/conf.d/z-php-local.ini
# php-fpmを設定したいときの指定
#      - ./www-local.conf:/usr/local/etc/php-fpm.d/z-www-local.conf
# rep2へhttps接続するための証明書の格納先の指定
#      - /etc/letsencrypt:/etc/letsencrypt
# 8080が待ち受けのポート番号(.envを作成しREP2_PORT=80と書いておくと80に変更出来る)
    ports:
      - "${REP2_PORT:-8080}:8443"
    network_mode: bridge
    restart: unless-stopped
    environment:
      TZ: "Asia/Tokyo"
# rep2で使用する暗号キーの指定
      SECRET_KEY: "${SECRET_KEY}"
# 2chproxy.plの設定
      NCPX_USER_AGENT: "Monazilla/1.00 (rep2+2chproxy.pl/0.1)"
      NCPX_ENABLE_ONLY_NCH_IO_UPGRADE: 1
      NCPX_ALLOW_CONNECT_METHOD: 1
      NCPX_KEEP_COOKIE : 0
      NCPX_ENABLE_WEB_SCRAPING : 0
