name: Build and Publish Docker

on:
  workflow_dispatch:
  push:
    branches:
      - php8
    paths-ignore:
      - '**.md'
  repository_dispatch:
    types: [p2-php-update]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log Upstream Trigger Info
        if: github.event.client_payload.run_id
        run: |
          echo "Triggered by p2-php run: https://github.com/fukumen/p2-php/actions/runs/${{ github.event.client_payload.run_id }}"
          echo "Source SHA: ${{ github.event.client_payload.sha }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare metadata
        id: meta
        run: |
          REPO_HASH=$(git rev-parse --short HEAD)
          echo "REPO_HASH=${REPO_HASH}" >> "$GITHUB_OUTPUT"
          REPO_RAW_LOG=$(git log -1 --format='%cd %s' --date=short)
          echo "REPO_LOG=$(echo -n "$REPO_RAW_LOG" | base64 -w 0)" >> "$GITHUB_OUTPUT"

          git clone --depth 1 --branch php8-merge-mbstring https://github.com/fukumen/p2-php.git temp_p2
          cd temp_p2
          
          REP2_HASH=$(git rev-parse --short HEAD)
          REP2_RAW_LOG=$(git log -1 --format='%cd %s' --date=short)
          
          echo "REP2_HASH=${REP2_HASH}" >> "$GITHUB_OUTPUT"
          echo "REP2_LOG=$(echo -n "$REP2_RAW_LOG" | base64 -w 0)" >> "$GITHUB_OUTPUT"
          
          cd ..
          rm -rf temp_p2

      # - name: Generate Date Tag
      #   id: date
      #   run: echo "::set-output name=today::$(date +'%y%m%d')"

      # Build rep2 (Standard)
      - name: Build and push rep2
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-contexts: |
            p2-rep2=https://github.com/fukumen/p2-php.git#php8-merge-mbstring
            2chproxy.pl=https://github.com/fukumen/2chproxy.pl.git#always-https-for-2ch-config
          build-args: |
            DEBUG=off
            REPO_HASH=${{ steps.meta.outputs.REPO_HASH }}
            REPO_LOG=${{ steps.meta.outputs.REPO_LOG }}
            REP2_HASH=${{ steps.meta.outputs.REP2_HASH }}
            REP2_LOG=${{ steps.meta.outputs.REP2_LOG }}
            RUN_ID=${{ github.run_id }}
            RUN_NUMBER=${{ github.run_number }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/rep2:latest
#            ghcr.io/${{ github.repository_owner }}/rep2:${{ steps.date.outputs.today }}

      # Build rep2-imagick (With ImageMagick)
      - name: Build and push rep2-imagick
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-contexts: |
            p2-rep2=https://github.com/fukumen/p2-php.git#php8-merge-mbstring
            2chproxy.pl=https://github.com/fukumen/2chproxy.pl.git#always-https-for-2ch-config
          build-args: |
            DEBUG=off
            USE_IMAGICK=true
            REPO_HASH=${{ steps.meta.outputs.REPO_HASH }}
            REPO_LOG=${{ steps.meta.outputs.REPO_LOG }}
            REP2_HASH=${{ steps.meta.outputs.REP2_HASH }}
            REP2_LOG=${{ steps.meta.outputs.REP2_LOG }}
            RUN_ID=${{ github.run_id }}
            RUN_NUMBER=${{ github.run_number }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/rep2-imagick:latest
#            ghcr.io/${{ github.repository_owner }}/rep2-imagick:${{ steps.date.outputs.today }}
