name: Build and Publish Docker

on:
  workflow_dispatch:
  push:
    branches:
      - php8
  repository_dispatch:
    types: [p2-php-update]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate Date Tag
      #   id: date
      #   run: echo "::set-output name=today::$(date +'%y%m%d')"

      # Build rep2 (Standard)
      - name: Build and push rep2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-contexts: |
            p2-rep2=https://github.com/fukumen/p2-php.git#php8-merge-mbstring
            2chproxy.pl=https://github.com/fukumen/2chproxy.pl.git#always-https-for-2ch-config
          build-args: |
            DEBUG=off
          tags: |
            ghcr.io/${{ github.repository_owner }}/rep2:latest
#            ghcr.io/${{ github.repository_owner }}/rep2:${{ steps.date.outputs.today }}

      # Build rep2-img (With ImageMagick)
      - name: Build and push rep2-img
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-contexts: |
            p2-rep2=https://github.com/fukumen/p2-php.git#php8-merge-mbstring
            2chproxy.pl=https://github.com/fukumen/2chproxy.pl.git#always-https-for-2ch-config
          build-args: |
            DEBUG=off
            USE_IMAGICK=true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rep2-img:latest
#            ghcr.io/${{ github.repository_owner }}/rep2-img:${{ steps.date.outputs.today }}
